### ISSUE TITLE
"You need to define two answer form fields in the Exit question" Alert

### ISSUE THREAD

**Issue by sweetticket** [ErwinHaasnoot/QRTEngine#38]
Is QRTEngine no longer compatible with the new Qualtrics updates? I am no longer able to run my studies (that used to work), even though nothing has changed in my code.

**Comment by ErwinHaasnoot** [comment]
It seems like in a recent update by Qualtrics, something about their API has changed that makes one of the validation checks throw up a false positive.. I'll need to look at that tonight.

**Comment by sweetticket** [comment]
Any update on this? I'm using QRTEngine for my research, so any kind of update would be helpful!

**Comment by ErwinHaasnoot** [comment]
Hi!

This issue is due to a bug introduced by Qualtrics into one of their
JavaScript APIs (getChoiceValue). We have released a version of the
QRTEngine that disables alert-box. There shouldn't any other issues with
the QRTEngine.

See: http://www.qrtengine.com/qualtrics-bug-work-around/
